spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5401/customers
    username: postgres
    password: mNK2AhLReAz9xPgm

  jpa:
    hibernate:
      ddl-auto: update
      
  application:
    name: customers

server:
  port: 0
  
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true