server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
  dashboard:
    path: /dashboard

spring:
  application:
    name: eureka-server
    